# #Workflow
##key: value
# title: Website name
# description: A website for uploading content
# #string, array, objects

# tags:
#     - technology
#     - images
#     - creative

# # indentation  matters

# address:
#     street: MG Road
#     city: Bng
#     state: kr

# # env variables
# value: ${{ env.Value}}
# variable: ${{ github.VariableName}}


name: Github action for
on: 
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Print Node Version
              run: node --version
            - name: Print Npm version
              run: npm --version